name: WarnPlayer
version: 1.0.0
api: [3.0.0]
author: MCrafters
main: WarnPlayer\Main
commands:
  warn:
    description: Warn A Player!
    permission: rank.moderator
  spectate:
    description: Spectate a player!
    permission: rank.moderator    
  report:
    description: report A Player!
permissions:
  rank.moderator:
    default: op
